## Final Project Submission

Please fill out:
* Student name: 
* Student pace: self paced / part time / full time
* Scheduled project review date/time: 
* Instructor name: 
* Blog post URL:

In [1]:
# Your code here - remember to use markdown cells for comments as well!
%ls

 Volume in drive C is OS
 Volume Serial Number is 9A45-0C78

 Directory of c:\Users\Jake\Documents\CapstoneTransplant\Capstone-Restaurant

04/15/2023  01:45 PM    <DIR>          .
04/11/2023  04:07 AM    <DIR>          ..
04/11/2023  04:17 AM             1,942 .gitignore
04/11/2023  07:01 AM    <DIR>          .ipynb_checkpoints
04/11/2023  08:46 AM    <DIR>          Data
04/11/2023  06:57 AM            60,277 First.ipynb
04/11/2023  04:07 AM                23 README.md
04/15/2023  02:06 PM           178,051 Second.ipynb
04/15/2023  02:52 PM            33,932 Third.ipynb
               5 File(s)        274,225 bytes
               4 Dir(s)  88,442,556,416 bytes free

In [2]:
import sqlite3
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
import json
import argparse
import collections
import scipy
import csv
plt.style.use('seaborn-notebook')
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import euclidean
from nltk.tokenize import TweetTokenizer
from nltk.corpus import stopwords, wordnet
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import RegexpTokenizer

In [3]:
df = pd.read_csv('Data/cleaned.csv')
df = pd.DataFrame(df)

In [4]:
df = pd.DataFrame(df)

In [5]:
df

,Unnamed: 0,name,state,stars,review_count,categories,AcceptsInsurance,ByAppointmentOnly,BusinessAcceptsCreditCards,BusinessParking_garage,...,Corkage,DietaryRestrictions_dairy-free,DietaryRestrictions_gluten-free,DietaryRestrictions_vegan,DietaryRestrictions_kosher,DietaryRestrictions_halal,DietaryRestrictions_soy-free,DietaryRestrictions_vegetarian,AgesAllowed,RestaurantsCounterService
0,3,"""Brick House Tavern + Tap""",OH,3.5,116,american new nightlife bar sandwich american t...,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
1,13,"""Showmars Government Center""",NC,3.5,7,restaurant american traditional,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2,26,"""Panera Bread""",OH,2.0,4,soup salad sandwich restaurant,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3,33,"""Brewster's Pub""",OH,4.0,4,nightlife pub bar,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
4,37,"""Yuzu""",OH,3.5,78,nightlife izakaya comfort food cocktail bar as...,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22380,151991,"""Asian Health Center""",OH,5.0,3,acupuncture health medical,2,2,1,2,...,2,2,2,2,2,2,2,2,2,2
22381,151997,"""Carlone's Candy and Ice Cream""",OH,4.0,3,cooking school specialty school food education...,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
22382,152012,"""Cole's Public House""",OH,4.5,21,bar gastropubs nightlife restaurant pub sandwich,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
22383,152030,"""CVS""",NC,2.0,5,drugstore shopping,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
22384,152037,"""Village Auto Body""",OH,5.0,3,body shop automotive,2,2,2,1,...,2,2,2,2,2,2,2,2,2,2

In [6]:
df1 = df[df['state'] == 'NC']
df2 = df[df['state'] != 'NC']

In [7]:
cols_of_interest = ['name', 'state', 'categories']

In [8]:
df1.drop(cols_of_interest, axis=1, inplace=True)

C:\Users\Jake\AppData\Local\Temp\ipykernel_42800\858306450.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(cols_of_interest, axis=1, inplace=True)

In [9]:
df2.drop(cols_of_interest, axis=1, inplace=True)

C:\Users\Jake\AppData\Local\Temp\ipykernel_42800\3128648895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(cols_of_interest, axis=1, inplace=True)

In [10]:
query_row = df2.iloc[0]
df2.iloc[0]

Unnamed: 0                          3
stars                             3.5
review_count                      116
AcceptsInsurance                    2
ByAppointmentOnly                   2
                                 ...
DietaryRestrictions_halal           2
DietaryRestrictions_soy-free        2
DietaryRestrictions_vegetarian      2
AgesAllowed                         2
RestaurantsCounterService           2
Name: 0, Length: 84, dtype: object

In [11]:
cols_to_drop = df2.select_dtypes(exclude=[float, int]).columns
cols_to_drop = df1.select_dtypes(exclude=[float, int]).columns

In [12]:
df1 = df1.drop(columns=cols_to_drop)
df2 = df2.drop(columns=cols_to_drop)

In [17]:
df1

,Unnamed: 0,stars,review_count,AcceptsInsurance,ByAppointmentOnly,BusinessAcceptsCreditCards,BusinessParking_garage,BusinessParking_street,BusinessParking_validated,BusinessParking_lot,...,Corkage,DietaryRestrictions_dairy-free,DietaryRestrictions_gluten-free,DietaryRestrictions_vegan,DietaryRestrictions_kosher,DietaryRestrictions_halal,DietaryRestrictions_soy-free,DietaryRestrictions_vegetarian,AgesAllowed,RestaurantsCounterService
1,13,3.5,7,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
5,39,3.5,3,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
6,52,5.0,4,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
8,62,5.0,5,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
10,72,4.0,17,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22375,151949,2.5,6,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
22377,151975,4.5,108,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
22378,151978,4.0,15,2,2,2,2,0,0,0,...,2,2,2,2,2,2,2,2,2,2
22379,151986,3.5,17,2,2,2,2,0,0,0,...,2,2,2,2,2,2,2,2,2,2
22383,152030,2.0,5,2,2,2,2,0,0,0,...,2,2,2,2,2,2,2,2,2,2

In [18]:
similarity_scores = cosine_similarity(df1, df2)
# get the index of the query_row in df1
query_index = df1.index.get_loc(6)

# sort the similarity_scores in descending order and get the top 5 indices
top_indices = similarity_scores[query_index].argsort()[::-1][:5]

# get the corresponding rows from df2
top_rows = df2.iloc[top_indices]

In [19]:
top_rows

,Unnamed: 0,stars,review_count,AcceptsInsurance,ByAppointmentOnly,BusinessAcceptsCreditCards,BusinessParking_garage,BusinessParking_street,BusinessParking_validated,BusinessParking_lot,...,Corkage,DietaryRestrictions_dairy-free,DietaryRestrictions_gluten-free,DietaryRestrictions_vegan,DietaryRestrictions_kosher,DietaryRestrictions_halal,DietaryRestrictions_soy-free,DietaryRestrictions_vegetarian,AgesAllowed,RestaurantsCounterService
7,57,5.0,3,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
9,64,3.5,3,2,2,2,2,0,0,0,...,2,2,2,2,2,2,2,2,2,2
12,81,3.5,4,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
13,83,4.0,16,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3,33,4.0,4,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

IndexError: index 86736506 is out of bounds for axis 0 with size 11317

NameError: name 'top_indices' is not defined